<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Libs\ConnectionLib.TaskTrackerService\ConnectionLib.TaskTrackerService.csproj" />
      <ProjectReference Include="..\..\Libs\Core\Core.csproj" />
      <ProjectReference Include="..\UserService.Domain\UserService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentResults" Version="4.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Auth\" />
    </ItemGroup>

</Project>
